baseURL = "https://roryshanshan.github.io/xcmobile/"
defaultContentLanguage = "en"
languageCode = "en"
title = "XC Mobile House"
theme = "dream"


[params]
enableMenu = true
github = { href = "https://github.com/g1eny0ung", title = "GitHub" }
favicon = "https://i.postimg.cc/sjj7ZykN/202504120804853.png"

lightTheme = "emerald"
darkTheme = "forest"

# backgroundImage = "https://i.postimg.cc/G3tYDFp6/202504112221048.png"
# backgroundImageDark = ""

author = "Gavin"
description = "XC MOBILE HOUSE--Manufacturer for mobile house"
avatar = "https://i.postimg.cc/G3tYDFp6/202504112221048.png"
headerTitle = "XC MOBILE HOUSE--Manufacturer for mobile house"
# motto = "Be your best supplier--Made IN CHINA"

footerBottomText = "Qingzhou County, Weifang City, Shandong Province"

# rss = true

# utterancesRepo = ""

# valine = true
# LEANCLOUD_APP_ID = ""
# LEANCLOUD_APP_KEY = ""

# waline = true
# walineServer = ""

email = "roryshanshan@gmail.com"

siteStartYear = 2016


# Syntax highlighting
# customSyntaxHighlighting = true

# options
stickyNav = true
# reorderNavItems =  ["about", "search", "rss", "posts", "categories", "tags"]
collapseNavItems = ["posts", "categories", "tags"]
noDefaultSummaryCover = true
showTableOfContents = true
showSummaryCoverInPost = true
imageZoomableInPost = true
# showPrevNextPost = true
reorderShares = ["x", "facebook", "whatsapp"]


[params.twikoo]
enabled = true
envID = ""
region = ""
lang = "en"

# [params.advanced]
# customCSS = ["css/custom.css"]
# customJS = []

# [params.experimental]
jsDate = true
jsDateFormat = "yyyy年MM月dd日"

[menu]
   [[menu.main]]
    identifier = "xc-catalog"
    name = "XC Catalog"
    url = "/xc-catalog"  # 指向站内页面或外部链接
    weight = 1

  [[menu.main]]
    identifier = "space-capsule"
    name = "Space Capsule"
    url = "/space-capsule/"  # 指向站内页面或外部链接
    weight = 2

  [[menu.main]]
    identifier = "apple-cabin"
    name = "Apple Cabin"
    url = "/apple-cabin/"
    weight = 3

  [[menu.main]]
    identifier = "kitchen-house"
    name = "Kitchen House"
    url = "/kitchen-house/"
    weight = 4

  [[menu.main]]
  name = "Other"
  identifier = "other"
  url = "/other/"
  weight = 5


enableRobotsTXT = true  # 详见 Dream 作者 docs 目录下文档
enableEmoji = true    
hasCJKLanguage = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

